language: objective-c
osx_image: xcode7.2
xcode_project: PDFGenerator.xcodeproj
xcode_scheme: PDFGenerator
xcode_sdk: iphonesimulator9.2
env:
  global:
  - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=9.1"
  - FRAMEWORK_NAME=PDFGenerator
before_install:
  - brew update
  - brew unlink carthage
  - brew install carthage
script:
  - pod lib lint
  - set -o pipefail
  - xctool -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -destination "$DESTINATION" test | xcpretty -c
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: YsKd2J0SaMmC2Y1YdDOS6gs3/zvLlMfz5J+1akpj5fzb/mKCWgh0zOo15PgvbFX+cPmF8avLEWrTq3vR9oxeB0xZuM31GsjzNheoP6Ie4lwRl875c0AqbxcAgGT9g/PNM8lSNucdp5F5wwQo9qzDbzjHNgcV+OAOgKyiDo1lq0/059g5NHABVKfwxFX7629vrv3dOUk6fZ1n6xbbfvaLS+qLCrWwvTWRjb62ghoq/sgexZLT7zoLMiMxU/lxDnPIP/ZDP9UVWcUvdW8FQH+JULwEIe5pOjwIWZEjEBGF9e/gQkJdnAU6AhkHdghsg8trI29e1d+9Tsr0pk5QZzBw5ZoAPxN2YDD89QuyXnkQyx/D2BdiCTElZbz8IS5L0pcFMzG2uoQCFEHpUWJ8/22VoYXG0g3pv2OHo9zylFFZBdEp8ie/cZ7o47tm4SYdFTNzec+UzwbgGGoiTra/pQWm69k9mf9NQzsB04iM7dehq9R+0EUMgZbMDVu6t5zxs6VfdRvfGXpwzx5CZVk7Fjg677FdR12zs+r2Ek5lqh66LXAWpExfMvGCRjYtQxYDU5e67dCjSlxG9EHUIbLfikdQveI1aHVguYEy+fF6HCZNgYWOQoUpgiCKMh7QG4qKrpN1pNRC6PTIiOS+izC2cJXcX9ngTkIEzCsZ3QJPkfNEn3w=
  file: PDFGenerator.framework.zip
  skip_cleanup: true
  on:
    repo: sgr-ksmt/PDFGenerator
    tags: true
notifications:
  email: false