language: objective-c
osx_image: xcode8
xcode_project: PDFGenerator.xcodeproj
xcode_scheme: PDFGenerator
env:
  global:
  - DESTINATION="platform=iOS Simulator,name=iPhone 7"
  - FRAMEWORK_NAME=PDFGenerator
branches:
  only:
  - master
  - "/bugfix.*/"
  - "/^develop.*/"
  - "/^v?[0-9\\.]+/"
script:
- if [[ "$JOB" == "Xcode7.3" ]]; then pod lib lint; fi
- set -o pipefail
- xcodebuild test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -sdk iphonesimulator -destination "$DESTINATION" | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
- carthage build --no-skip-current
- carthage archive "$FRAMEWORK_NAME"
deploy:
  provider: releases
  api_key:
    secure: so2Gb/rudIxqUq5dP392m7u43RjPDXkpymoFJ/MgBVXRGb9HiWy5D/9ontGtZGC4E71lJBmnA+laHQKSpWdgjphGitpezP3Sd9KGWrYy1cqsVGiv3C511QS31DX0zw/jUaMAOE21ycTKHZBoXTPa+GPh18myxZd4E9QIUOClz83l/XeZSEKlf08KndjyjwW4NdTB1b4S/QWfWM3CJvHAHAbx2T3AYHCl6GeYNxNnplU4rWE6mEE+GAo3pZQnn9iYmJZkFCADWxMmkYNfkqPJEkL1qFCf8nnxZq9DtqZLZs3aY0uW05p8heJSNJzS6jqP6/aqnWwCPp+JYoNK7ci8Unrsj6VvaqdvfLWXNSO9LHHM23Fdx/wRSw5PCCa7V7MOYFydAjex+DhuFSlq37MOhF/SXA2iYRXV9BT1u/b+feofLimroM2EEk336kR3t5B9bP1qjnQC3b0UMoa7ngosMg5wN/+PJ3u45m3/9qFi/JdB4nkG2TqKGIgcIRLU/NFJNOM0xVxXh1Oe5kvILJ01ChnJzvKcX5M6AHMDio4PApDSpQ81LHRr5J6kgxh9j4Lzd1ErQ4d4EP8B5RhSTYXcRUzp6aL5NpKm+kYVxIuRn71Gy/vjc9gqe4RYAnXXygiwnpMkn50HsUb+iWG8t5RvRy9MFi8mlkdMqCF1mRZZs3M=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: "$TRAVIS_REPO_SLUG"
    tags: true
notifications:
  email: false
  slack:
    secure: Z4S7jnJk1nesu1FK13218coFrEqBSI+P5ruDA9FNgU72A06fh/kRCLrBPJhjQGzQXR4n8kCONXC3SJULYWRivF8M/E2hox88j0+Ii5mzPIfUWD6WejXtJQ/yu9djq3TbXNoK0rCsAU4rkLnfYSYifgYayudW/ZjFjOWPmQ+SqYG5bTmTk501EU6uD6OcDrWpKUbA9neG2RJI3LRyiDNxwm+3XeNZJRlD/vhD1xnx4obv8T2yF+zr3rSL33LqP0aR2djjTGQhg67mWUiZTcbW6n+zJDI+BCB6ZsTs3itJObbgkvuOa1e25V4DXjcj5A5t4R564IJ/OjBePaC/GRo46Gm3enLEN71OXhEKjkQDZzorWOiEMo3GAJmQZmKsukSDu8iG6kfC07+4bVS3Qf4M7lIOJbRC2SwvycCfVJDT/uexG2yX5+bVYKBHBIx6w2dRDscoRsiQ6wbO2ZbSjzfUbVKmWDYSkopRQaA/rZ/GwAJDVMWINeGqhvnN6CPRBHa8rtd6XAmAhX+GQA1UCh6Cx6Bn2FyVdj+2kH/AoIjjMTv8itzCU9cPvLIBNMcQywjZkZoIbrHjmSa+I+KELSNRgkVUxgBNO2NnfiuxApjOjNN+iNmlZszsO74X+0Rq0/xiJizuISEz6LEEaozcV9DDsjNPc5WqkrZGhuqFLYpT86Y=
